### ISSUE TITLE
BOM question

### ISSUE THREAD

**Issue by Genmaizen** [BleepSound/ms20-vcf-double#2]
Hi BleepSound, 
Thank you very much for this project! I am planning to build this. As I am just a beginner in the DIY Eurorack hobby, I have some questions concerning the BOM: 

- What parts exactly are FB1 and FB2? 
- SW1 and SW3 are momentary switches i.e. push buttons. Or just switches like SW2?
- D7 is a 4 mm LED. Is it ok to just take a 3 mm LED?

Thanks very much  and cheers, 
Genmaizen

**Comment by arthursaunier** [comment]
Hi!
Sorry for the late reply

- What parts exactly are FB1 and FB2?
They are ferrite beads, you can replace them by a straight wire if you want. (They're used to filter the power supply, they are not really mandatory).
- SW1 and SW3 are momentary switches i.e. push buttons. Or just switches like SW2?
SWI and SW3 are SPDT switches, not momentary switches, i'll switch the description in the bom. You can use this [model](https://www.taydaelectronics.com/mini-toggle-switch-1m-series-dpdt-on-on.html).
- D7 is a 4 mm LED. Is it ok to just take a 3 mm LED?
- Yup fine with a 3mm LED
Cheers

**Comment by Genmaizen** [comment]
Thank you very much for the info! Looking forward to building the filter... 😊
